language: rust
cache: cargo
matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: 1.31.0
    - os: osx
      rust: stable
    - os: osx
      rust: 1.31.0
script:
  - cargo run
